# Generated by Django 5.2.14 on 2026-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_sharedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="client_files_need_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="provider_files_need_approval",
            field=models.BooleanField(default=True),
        ),
    ]
