# Generated by Django 5.2.14 on 2026-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatroom_client_files_need_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="provider_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
