# Generated by Django 5.2.14 on 2026-05-27 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatroom_provider_joined_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="provider",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="providers",
            field=models.ManyToManyField(
                blank=True, related_name="provider_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
