# Generated by Django 5.2.14 on 2026-05-31 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_remove_chatroom_provider_chatroom_providers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="extra_clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="extra_client_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
