# Generated by Django 5.2.14 on 2026-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chatroom_extra_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="target",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("client", "Client only"),
                    ("provider", "Provider only"),
                ],
                default="everyone",
                max_length=10,
            ),
        ),
    ]
