# Generated by Django 5.2.14 on 2026-06-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_message_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="target",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("client", "Client only"),
                    ("provider", "Provider only"),
                    ("admin", "Admin only"),
                ],
                default="everyone",
                max_length=10,
            ),
        ),
    ]
