# Generated by Django 5.2.14 on 2026-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_message_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="negotiation_mode",
            field=models.BooleanField(default=False),
        ),
    ]
