# Generated by Django 5.2.14 on 2026-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_chatroom_negotiation_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="chatroom",
            name="course",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
