# Generated by Django 5.2.14 on 2026-05-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="client_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialisation", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                (
                    "rate_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rate_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
