# Generated by Django 5.2.14 on 2026-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_device_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
