# Generated by Django 5.2.14 on 2026-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_qrlinksession"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomaccesstoken",
            name="pin",
            field=models.CharField(default="00000", editable=False, max_length=5),
            preserve_default=False,
        ),
    ]
