# Generated by Django 5.2.14 on 2026-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_roomaccesstoken_pin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderNumberCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="provider_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
